require 'forwardable'
require 'linguistics_latin'
require 'linguistics_latin_tense_block/version'
require 'linguistics_latin_tense_block/tense_block'
require 'linguistics_latin_tense_block/tense_block/null_tense_block'
require 'linguistics_latin_tense_block/tense_block/vector_resolution_delegate'
